import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {parse} from 'acorn';
import * as parse5 from 'parse5';
import '../assets/js/form-feedback-core.js';
import {auditFormFeedbackDocument} from '../scripts/audit-form-feedback.mjs';
const core=globalThis.DongDaFormFeedbackCore,read=path=>fs.readFile(new URL('../'+path,import.meta.url),'utf8');
const source=await read('index.html'),document=parse5.parse(source),inline=[];
function walk(node){if(node.tagName==='script'&&!node.attrs.some(a=>a.name==='src')){const type=node.attrs.find(a=>a.name==='type')?.value;if(!type||['text/javascript','application/javascript','module'].includes(type))inline.push(node.childNodes.map(n=>n.value||'').join(''));}for(const child of node.childNodes||[])walk(child);}walk(document);
const functions=new Map();for(const script of inline)for(const node of parse(script,{ecmaVersion:'latest'}).body)if(node.type==='FunctionDeclaration')functions.set(node.id.name,script.slice(node.start,node.end));
const controllerSource=await read('assets/js/form-feedback-ui.js'),coreSource=await read('assets/js/form-feedback-core.js');
function fixture(){
  const nodes=new Map(),listeners={},status=[];
  class Element{
    constructor(id='',tag='INPUT',scope=true){this.id=id;this.tagName=tag;this.scope=scope;this.attrs=new Map();this.classes=new Set();this.classList={add:key=>this.classes.add(key),contains:key=>this.classes.has(key)};this.value='';this.valid=true;this.validity={typeMismatch:false};this.textContent='';this.hidden=false;this.children=[];this.parentElement=null;this.checked=false;}
    setAttribute(key,value){this.attrs.set(key,String(value));}getAttribute(key){return this.attrs.get(key)??null;}removeAttribute(key){this.attrs.delete(key);}
    checkValidity(){return this.valid;}focus(){this.focused=true;}
    appendChild(child){this.children.push(child);child.parentElement=this;if(child.id)nodes.set(child.id,child);return child;}
    insertAdjacentElement(position,child){assert.equal(position,'afterend');(this.parentElement||container).appendChild(child);}
    closest(selector){if(selector==='details')return details;if(selector==='.sample-ack')return this.id==='sample-costTermsAcknowledged'?ack:null;if(selector.startsWith('#iform'))return this.scope?container:null;return this.parentElement||container;}
    querySelectorAll(){return Array.from(nodes.values()).filter(node=>['INPUT','SELECT','TEXTAREA'].includes(node.tagName));}
  }
  const container=new Element('container','DIV'),details=new Element('details','DETAILS'),ack=new Element('ack','LABEL');container.appendChild(ack);details.open=false;
  const scope={console,Map,WeakMap,Set,document:{getElementById:id=>nodes.get(id)||null,createElement:tag=>new Element('',tag.toUpperCase()),addEventListener:(name,callback)=>{listeners[name]=callback;},querySelectorAll:()=>container.querySelectorAll(),querySelector:()=>container.querySelectorAll()[0]||null},lang:'en',setLeadStatus:(...args)=>status.push(args),rfqText:key=>key,fieldValue:id=>nodes.get(id)?.value.trim()||'',esc:value=>String(value),localText:value=>value.en||value,crypto:{},sessionStorage:{setItem(){},removeItem(){},getItem(){return null;}}};
  scope.window=scope;vm.createContext(scope);vm.runInContext(coreSource,scope);vm.runInContext(controllerSource,scope);
  function input(id,{tag='INPUT',value='',valid=true,typeMismatch=false,scoped=true}={}){const element=new Element(id,tag,scoped);element.value=value;element.valid=valid;element.validity.typeMismatch=typeMismatch;container.appendChild(element);return element;}
  return {scope,nodes,container,details,ack,listeners,status,input,ui:scope.DongDaFieldFeedback,load:name=>vm.runInContext(functions.get(name),scope)};
}
test('field copy is immutable and every code has zh/en/ru text',()=>{assert.ok(Object.isFrozen(core)&&Object.isFrozen(core.copy));for(const locale of ['en','zh','ru']){assert.ok(Object.isFrozen(core.copy[locale]));assert.deepEqual(Object.keys(core.copy[locale]),Object.keys(core.copy.en));for(const code of Object.keys(core.copy.en))assert.ok(core.message(code,locale,10).length>0);}});
test('five existing languages and inherited-property names fall back to English',()=>{for(const locale of ['kk','ky','tg','tk','uz','toString','__proto__'])assert.equal(core.message('email',locale),core.message('email','en'));assert.throws(()=>core.message('constructor','en'));});
test('minimum copy accepts only the existing bounded integer quantity',()=>{assert.match(core.message('minimum','en',1000000000),/1000000000/);for(const value of [0,-1,1.5,1000000001,NaN,Infinity,'1',true,undefined])assert.throws(()=>core.message('minimum','zh',value),/Invalid feedback minimum/);});
test('native contact result keeps whitespace, type and validity behavior',()=>{assert.equal(core.contactError({value:' \n ',valid:true,typeMismatch:false}),'required');assert.equal(core.contactError({value:'bad',valid:false,typeMismatch:true}),'email');assert.equal(core.contactError({value:'ok',valid:true,typeMismatch:false}),null);assert.equal(core.contactError({value:'x',valid:false,typeMismatch:false}),'invalid');});
test('native result rejects unknown fields and malformed flags',()=>{for(const value of [null,[],{}, {value:'x',valid:true,typeMismatch:false,extra:true},{value:1,valid:true,typeMismatch:false},{value:'x',valid:'true',typeMismatch:false},{value:'x',valid:true}])assert.throws(()=>core.contactError(value));});
test('messages map the real domain error codes without another domain validator',()=>{for(const value of ['integer','quantity'])assert.equal(core.configurationCode(value),'quantity');assert.equal(core.configurationCode('minimum'),'minimum');assert.equal(core.configurationCode('required'),'choose');assert.equal(core.configurationCode('unknown'),'invalid');for(const key of ['length','width','height','loadKg'])assert.equal(core.customizationCode(key),'decimal');assert.equal(core.customizationCode('printColors'),'colors');assert.equal(core.customizationCode('customization'),'invalid');});
test('new errors use text and one described-by token while retaining hints',()=>{const f=fixture(),el=f.input('fi1');el.setAttribute('aria-describedby','existing-hint');f.ui.show(el,'required');f.ui.show(el,'email');assert.equal(el.getAttribute('aria-describedby'),'existing-hint fi1-error');assert.equal(f.nodes.get('fi1-error').textContent,core.message('email','en'));assert.equal(f.container.children.filter(n=>n.id==='fi1-error').length,1);assert.equal(el.getAttribute('aria-invalid'),'true');f.ui.clear(el);assert.equal(el.getAttribute('aria-describedby'),'existing-hint');assert.equal(el.getAttribute('aria-invalid'),null);assert.equal(f.nodes.get('fi1-error').hidden,true);});
test('quote errors reuse their original span and described-by ownership',()=>{const f=fixture(),el=f.input('q-spec-qty'),span=f.input('q-spec-qty-error',{tag:'SPAN'});span.classes.add('q-field-error');el.setAttribute('aria-describedby',span.id);f.ui.show(el,'minimum',10);f.ui.clear(el);assert.equal(el.getAttribute('aria-describedby'),span.id);assert.equal(span.hidden,true);});
test('contact correction remains invalid until native validity succeeds',()=>{const f=fixture(),el=f.input('fi3',{value:'bad',valid:false,typeMismatch:true});f.ui.show(el,'email');f.listeners.input({target:el});assert.equal(el.getAttribute('aria-invalid'),'true');el.value='buyer@example.test';el.valid=true;el.validity.typeMismatch=false;f.listeners.input({target:el});assert.equal(el.getAttribute('aria-invalid'),null);assert.equal(f.status.length,0);});
test('language and recreated controls retain codes but never copy buyer values',()=>{const f=fixture(),el=f.input('rfq-line-test-qty',{value:'private sentinel'});f.ui.show(el,'quantity');f.scope.lang='ru';f.nodes.delete(el.id+'-error');const next=f.input(el.id,{value:el.value});f.ui.sync();const span=f.nodes.get(el.id+'-error');assert.equal(span.textContent,core.message('quantity','ru'));assert.doesNotMatch(span.textContent,/private sentinel/);assert.equal(next.getAttribute('aria-invalid'),'true');f.nodes.delete(next.id);f.ui.sync();const fresh=f.input(next.id);f.ui.sync();assert.equal(fresh.getAttribute('aria-invalid'),null);});
test('foreign surfaces and honeypots are ignored and collisions fail closed',()=>{const f=fixture();assert.equal(f.ui.show(f.input('outside',{scoped:false}),'required'),null);assert.equal(f.ui.show(f.input('sample-honeypot'),'required'),null);assert.equal(f.ui.show(f.input('fi_hp'),'required'),null);const el=f.input('fi1');f.input('fi1-error',{tag:'SPAN'});assert.throws(()=>f.ui.show(el,'required'),/collision/);});
test('memory-only field records have an explicit finite bound',()=>{const f=fixture();for(let i=0;i<core.maxFields;i++)f.ui.show(f.input('rfq-bounded-'+i),'required');assert.throws(()=>f.ui.show(f.input('rfq-over-limit'),'required'),/Too many/);f.ui.clearWithin(f.container);assert.doesNotThrow(()=>f.ui.show(f.input('fi1'),'required'));});
test('actual shared contact validator describes errors, focuses first and rejects missing DOM',()=>{const f=fixture();f.load('validateContactFields');const company=f.input('fi1'),email=f.input('fi3',{value:'bad',valid:false,typeMismatch:true});assert.equal(f.scope.validateContactFields(['fi1','fi3'],'lead-status'),false);assert.equal(company.focused,true);assert.equal(f.nodes.get('fi3-error').textContent,core.message('email','en'));company.value='Fixture';email.value='buyer@example.test';email.valid=true;email.validity.typeMismatch=false;assert.equal(f.scope.validateContactFields(['fi1','fi3'],'lead-status'),true);assert.equal(f.scope.validateContactFields(['missing'],'lead-status'),false);});
test('actual quote configuration reuses the existing validator and minimum',async()=>{
  const f=fixture();vm.runInContext(await read('assets/js/catalog-core.js'),f.scope);vm.runInContext(await read('assets/js/procurement-core.js'),f.scope);
  const catalog=f.scope.DongDaCatalog.create(JSON.parse(await read('content/products.json'))),product=catalog.resolve('valve-bags');
  f.scope.Q_PRODUCTS=catalog.all;f.scope.qState={prodId:product.id,specs:{qty:'0'},customization:null};f.scope.customValidation=()=>null;
  f.nodes.set('q-spec-fields',f.container);f.input('q-spec-status',{tag:'P'});for(const config of product.configuration)f.input('q-spec-'+config.id);f.load('qValidateSpecs');
  assert.equal(f.scope.DongDaProcurement.validateConfiguration(product,{qty:'0'}).qty,'minimum');
  assert.equal(f.scope.qValidateSpecs(),false);assert.equal(f.nodes.get('q-spec-qty-error').textContent,core.message('minimum','en',f.scope.DongDaProcurement.minimumQuantity(product)));assert.equal(f.nodes.get('q-spec-'+product.configuration[0].id).focused,true);
  f.scope.qState.specs.qty='1.5';assert.equal(f.scope.qValidateSpecs(),false);assert.equal(f.nodes.get('q-spec-qty-error').textContent,core.message('quantity','en'));
  const later=f.input('q-custom-length');f.scope.customValidation=()=>later;f.scope.qValidateSpecs();assert.notEqual(later.focused,true);assert.equal(f.nodes.get('q-spec-'+product.configuration[0].id).focused,true);
});
test('actual customization errors open details with precise decimal and print messages',async()=>{const f=fixture();vm.runInContext(await read('assets/js/customization-core.js'),f.scope);vm.runInContext(await read('assets/js/customization-ui.js'),f.scope);f.input('q-custom-length');f.input('q-custom-printColors');const value=Object.assign({},f.scope.DongDaCustomization.defaults,{length:'-1',printColors:'17'});assert.equal(f.scope.customValidation(value,'q-custom').id,'q-custom-length');assert.equal(f.details.open,true);assert.equal(f.nodes.get('q-custom-length-error').textContent,core.message('decimal','en'));assert.equal(f.nodes.get('q-custom-printColors-error').textContent,core.message('colors','en'));});
test('actual sample validation and correction preserve acknowledgement and never submit invalid needs',async()=>{
  const f=fixture();for(const file of ['sample-request-core','sample-request-copy','sample-request-ui'])vm.runInContext(await read('assets/js/'+file+'.js'),f.scope);
  f.scope.validateContactFields=()=>true;f.scope.catalog={resolve:()=>({kind:'product'})};f.scope.sampleState.productId='valve-bags';
  for(const key of Object.keys(f.scope.DongDaSampleRequest.limits))f.input('sample-'+key,{value:['purpose','recipientName','recipientPhone','country','city','address'].includes(key)?'fixture':key==='quantity'?'0':''});
  const ack=f.input('sample-costTermsAcknowledged');f.nodes.set('sample-form',f.container);await f.scope.submitSampleRequest({preventDefault(){}});
  assert.equal(f.nodes.get('sample-quantity').focused,true);assert.equal(f.nodes.get('sample-costTermsAcknowledged-error').textContent,core.message('acknowledge','en'));
  f.nodes.get('sample-quantity').value='1';f.scope.refreshSampleFeedback('sample-quantity');assert.equal(f.nodes.get('sample-quantity').getAttribute('aria-invalid'),null);
  ack.checked=true;f.listeners.change({target:ack});assert.equal(ack.getAttribute('aria-invalid'),null);assert.equal(f.scope.sampleState.busy,false);assert.equal(f.scope.sampleState.receipt,null);
});
test('actual RFQ validation associates independent item messages before any submission',async()=>{
  const f=fixture();for(const file of ['catalog-core','procurement-core','rfq-list-ui'])vm.runInContext(await read('assets/js/'+file+'.js'),f.scope);
  f.scope.catalog=f.scope.DongDaCatalog.create(JSON.parse(await read('content/products.json')));f.scope.DONGDA_LIST_COPY={en:{invalid:'invalid'}};f.scope.customValidation=()=>null;
  f.scope.rfqListState.items=[{lineId:'line-fixture',productId:'valve-bags',specifications:{qty:'0'}}];f.nodes.set('rfq-list-items',f.container);
  const product=f.scope.catalog.resolve('valve-bags');for(const config of product.configuration)f.input('rfq-line-fixture-'+config.id);await f.scope.submitRfqList({preventDefault(){}});
  assert.equal(f.nodes.get('rfq-line-fixture-qty-error').textContent,core.message('minimum','en',f.scope.DongDaProcurement.minimumQuantity(product)));assert.equal(f.scope.rfqListState.busy,false);assert.equal(f.scope.rfqListState.receipt,null);
  f.scope.rfqListState.items[0].specifications.qty='1.5';await f.scope.submitRfqList({preventDefault(){}});assert.equal(f.nodes.get('rfq-line-fixture-qty-error').textContent,core.message('quantity','en'));
});
test('static audit preserves one dependency chain, all four forms and six dialogs',()=>{assert.equal(auditFormFeedbackDocument(document),true);assert.throws(()=>auditFormFeedbackDocument(parse5.parse(source.replace('assets/js/form-feedback-ui.js','assets/js/missing.js'))));assert.throws(()=>auditFormFeedbackDocument(parse5.parse(source.replace('id="sample-form"','id="missing-form"'))));});
test('feedback adapter has no personal-value store, HTML interpolation or network/storage engine',()=>{assert.doesNotMatch(controllerSource,/\.innerHTML|\bfetch\s*\(|localStorage|sessionStorage|XMLHttpRequest|sendBeacon|\.set\([^\n]*\.value/);assert.doesNotMatch(coreSource,/localStorage|sessionStorage|\bfetch\s*\(/);});
