import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as parse5 from 'parse5';
import '../assets/js/public-motion.js';
import {auditMotionDocument} from '../scripts/audit-public-motion.mjs';
const motion=globalThis.DongDaPublicMotion;
const events=()=>{const listeners=new Map();return{addEventListener(type,fn){if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type).add(fn);},removeEventListener(type,fn){listeners.get(type)?.delete(fn);},emit(type){for(const fn of listeners.get(type)||[])fn();},count(){return [...listeners.values()].reduce((n,set)=>n+set.size,0);}};};
function node(classes='rv',page=null,parent={}){
  const list=new Set(classes.split(' '));return{isConnected:true,parentNode:parent,style:{transitionDelay:''},classList:{add(...keys){keys.forEach(key=>list.add(key));},remove(...keys){keys.forEach(key=>list.delete(key));},contains(key){return list.has(key);}},closest(){return page;},matches(selector){return selector.split(',').some(key=>list.has(key.slice(1)));}};
}
function fixture(options={}){
  const jobs=new Map(),observers=[],pool=[],document=Object.assign(events(),{hidden:false,documentElement:{dataset:{}},querySelectorAll(selector){return pool.filter(el=>el.matches(selector)&&el.isConnected);}});
  const media=Object.assign(events(),{matches:Boolean(options.reduced)}),host=Object.assign(events(),{document,matchMedia(){return media;},requestAnimationFrame(fn){const id=jobs.size+1;jobs.set(id,fn);return id;},cancelAnimationFrame(id){jobs.delete(id);}});
  if(options.legacy){const add=media.addEventListener,remove=media.removeEventListener;media.addListener=fn=>add('legacy',fn);media.removeListener=fn=>remove('legacy',fn);media.addEventListener=undefined;media.removeEventListener=undefined;}
  if(!options.missing)host.IntersectionObserver=class{constructor(callback){if(options.constructorFailure)throw Error('Unavailable');this.callback=callback;this.observed=new Set();this.unobserved=[];observers.push(this);}observe(el){if(options.observeFailure)throw Error('Unavailable');this.observed.add(el);}unobserve(el){this.observed.delete(el);this.unobserved.push(el);}disconnect(){this.observed.clear();}};
  const controller=motion.createController(host);return{host,document,media,pool,jobs,observers,controller,flush(){const callbacks=[...jobs.values()];jobs.clear();callbacks.forEach(fn=>fn());},change(value){media.matches=value;media.emit(options.legacy?'legacy':'change');}};
}
test('motion version and finite selector ownership are immutable',()=>{assert.ok(Object.isFrozen(motion));assert.equal(motion.version,'2026.10.09-motion-v1');assert.match(motion.selector,/\.rv-title/);assert.match(motion.selector,/\.fac-cell/);});
test('normal refresh coalesces and owns one observer only for active nodes',()=>{const f=fixture(),page=node('page on'),hidden=node('page');const visible=node('rv',page),other=node('rv',hidden);f.pool.push(visible,other);f.controller.refresh();f.controller.refresh();assert.equal(f.jobs.size,1);f.flush();assert.equal(f.observers.length,1);assert.ok(f.observers[0].observed.has(visible));assert.ok(!f.observers[0].observed.has(other));f.controller.refresh();f.flush();assert.equal(f.observers.length,1);f.controller.destroy();});
test('intersecting nodes reveal once and release will-change through their pending class',()=>{const f=fixture(),el=node('fac-cell');f.pool.push(el);f.controller.refresh();f.flush();assert.ok(el.classList.contains('dd-motion-pending'));f.observers[0].callback([{target:el,isIntersecting:false}]);assert.ok(!el.classList.contains('is-visible'));f.observers[0].callback([{target:el,isIntersecting:true}]);assert.ok(el.classList.contains('is-visible'));assert.ok(!el.classList.contains('dd-motion-pending'));assert.equal(f.observers[0].observed.size,0);f.controller.refresh();f.flush();assert.equal(f.observers[0].observed.size,0);f.controller.destroy();});
test('bounded CSS stagger is grouped by parent identity not matching class names',()=>{const f=fixture(),parent={},other={};for(let i=0;i<5;i++)f.pool.push(node('hnav-card',null,parent));f.pool.push(node('hnav-card',null,other));f.controller.refresh();f.flush();assert.deepEqual(f.pool.map(el=>el.style.transitionDelay),['0.00s','0.08s','0.16s','0.24s','0.00s','0.00s']);f.controller.destroy();});
test('page switches release old nodes without hiding completed content',()=>{const f=fixture(),first=node('page on'),second=node('page'),a=node('rv',first),b=node('rv',second);f.pool.push(a,b);f.controller.refresh();f.flush();first.classList.remove('on');second.classList.add('on');f.controller.refresh();f.flush();assert.ok(f.observers[0].unobserved.includes(a));assert.ok(a.classList.contains('in'));assert.ok(f.observers[0].observed.has(b));assert.ok(!a.classList.contains('dd-motion-pending'));f.controller.destroy();});
test('removed and newly rendered nodes do not accumulate or create more observers',()=>{const f=fixture(),old=node('rv');f.pool.push(old);f.controller.refresh();f.flush();old.isConnected=false;const fresh=node('pl2');f.pool.push(fresh);f.controller.refresh();f.flush();assert.ok(!f.observers[0].observed.has(old));assert.ok(f.observers[0].observed.has(fresh));assert.equal(f.observers.length,1);f.controller.destroy();});
test('initial reduced motion shows all content without frame or observer',()=>{const f=fixture({reduced:true}),hidden=node('page'),el=node('rv',hidden);f.pool.push(el);f.controller.refresh();assert.equal(f.jobs.size,0);assert.equal(f.observers.length,0);assert.ok(el.classList.contains('in'));assert.equal(f.document.documentElement.dataset.ddMotion,'static');f.controller.destroy();});
test('live preference cancels queued work and never re-hides already shown nodes',()=>{const f=fixture(),el=node('rv');f.pool.push(el);f.controller.refresh();f.change(true);assert.equal(f.jobs.size,0);assert.ok(el.classList.contains('in'));f.change(false);assert.equal(f.observers.length,1);assert.equal(f.observers[0].observed.size,0);f.controller.destroy();});
test('legacy media listeners receive preference changes and are removed on destroy',()=>{const f=fixture({legacy:true}),el=node('rv');f.pool.push(el);f.controller.refresh();f.flush();f.change(true);assert.ok(el.classList.contains('in'));f.controller.destroy();assert.equal(f.media.count(),0);});
test('missing observer and requestAnimationFrame fail open rather than blocking content',()=>{const f=fixture({missing:true}),el=node('rv');f.host.requestAnimationFrame=undefined;f.pool.push(el);f.controller.refresh();assert.ok(el.classList.contains('in'));assert.equal(f.document.documentElement.dataset.ddMotion,'static');f.controller.destroy();});
test('constructor and observe failures reveal content and prevent repeated failing retries',()=>{for(const key of ['constructorFailure','observeFailure']){const f=fixture({[key]:true}),el=node('rv');f.pool.push(el);f.controller.refresh();f.flush();assert.ok(el.classList.contains('in'));assert.equal(f.document.documentElement.dataset.ddMotion,'static');f.controller.refresh();f.flush();assert.ok(!el.classList.contains('dd-motion-pending'));f.controller.destroy();}});
test('hidden documents and pagehide release pending work and pageshow resumes safely',()=>{const f=fixture(),el=node('rv');f.pool.push(el);f.controller.refresh();f.flush();f.document.hidden=true;f.document.emit('visibilitychange');assert.equal(f.observers[0].observed.size,0);assert.ok(el.classList.contains('in'));f.document.hidden=false;f.host.emit('pageshow');f.flush();assert.equal(f.document.documentElement.dataset.ddMotion,'animated');f.controller.refresh();f.host.emit('pagehide');assert.equal(f.jobs.size,0);f.controller.destroy();});
test('destroy clears pending callbacks and listeners and late refresh is inert',()=>{const f=fixture(),el=node('rv');f.pool.push(el);f.controller.refresh();f.controller.destroy();f.controller.destroy();assert.equal(f.jobs.size,0);assert.equal(f.host.count(),0);assert.equal(f.document.count(),0);assert.equal(f.media.count(),0);assert.ok(el.classList.contains('in'));f.controller.refresh();assert.equal(f.jobs.size,0);});
test('static CSS and ownership audit reject missing dependencies and duplicate legacy code',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),css=await readFile(new URL('../assets/css/public-motion.css',import.meta.url),'utf8'),js=await readFile(new URL('../assets/js/public-motion.js',import.meta.url),'utf8');assert.equal(auditMotionDocument(parse5.parse(html)),true);assert.throws(()=>auditMotionDocument(parse5.parse(html.replace('assets/js/public-motion.js','assets/js/missing.js'))));assert.throws(()=>auditMotionDocument(parse5.parse(html.replace('</body>','<script>new IntersectionObserver()</script></body>'))));assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/animation:none!important/);assert.match(css,/will-change:auto/);assert.doesNotMatch(js,/fetch\(|sessionStorage|localStorage|innerHTML|setInterval|setTimeout|scroll.*addEventListener/);});
