import { readFile, writeFile, access } from 'node:fs/promises';
import { Search, X, ArrowRight, ArrowLeft, ArrowUp, Download, FileText, SlidersHorizontal, Columns3, ListPlus, ClipboardList, Trash2, Pencil, ZoomIn, ZoomOut, Maximize2, Scan } from 'lucide';
import '../assets/js/catalog-core.js';
import '../assets/js/catalog-copy.js';
import '../assets/js/product-inspection-core.js';
import '../assets/js/product-page-core.js';
import '../assets/js/industry-core.js';
import '../assets/js/resource-core.js';
import '../assets/js/insight-core.js';
import '../assets/js/faq-core.js';
import { resourceDeliveryData } from './resource-delivery-data.mjs';

const root = new URL('../', import.meta.url);
const products = JSON.parse(await readFile(new URL('content/products.json', root), 'utf8'));
const catalog = globalThis.DongDaCatalog.create(products);
const settings = JSON.parse(await readFile(new URL('content/site-settings.json', root), 'utf8'));
const industries = JSON.parse(await readFile(new URL('content/industries.json', root), 'utf8'));
globalThis.DongDaIndustry.create(industries, catalog);
const resources = JSON.parse(await readFile(new URL('content/resources.json', root), 'utf8'));
const resourceRegistry=globalThis.DongDaResources.create(resources, catalog);
const insights = JSON.parse(await readFile(new URL('content/insights.json', root), 'utf8'));
const insightRegistry=globalThis.DongDaInsights.create(insights, catalog);
const faqs=JSON.parse(await readFile(new URL('content/faqs.json',root),'utf8'));
globalThis.DongDaFAQ.create(faqs,catalog,insightRegistry);
for (const product of catalog.all) await access(new URL(product.image, root));
const icons = { Search, X, ArrowRight, ArrowLeft, ArrowUp, Download, FileText, SlidersHorizontal, Columns3, ListPlus, ClipboardList, Trash2, Pencil, ZoomIn, ZoomOut, Maximize2, Scan };
globalThis.DONGDA_CATALOG_ICONS = icons;
const safeJson = value => JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
await writeFile(new URL('assets/js/catalog-data.js', root),
  '// Generated by scripts/build-catalog.mjs from content/products.json. Do not edit.\n' +
  `globalThis.DONGDA_CATALOG_DATA=${safeJson(products)};\nglobalThis.DONGDA_CATALOG_ICONS=${safeJson(icons)};\nglobalThis.DONGDA_PUBLIC_SEO=${safeJson(settings.seo)};\nglobalThis.DONGDA_INDUSTRY_DATA=${safeJson(industries)};\nglobalThis.DONGDA_RESOURCE_DATA=${safeJson(resources)};\nglobalThis.DONGDA_RESOURCE_FILES=${safeJson(resourceDeliveryData(resourceRegistry))};\nglobalThis.DONGDA_INSIGHT_DATA=${safeJson(insights)};\nglobalThis.DONGDA_FAQ_DATA=${safeJson(faqs)};\n`);
await writeFile(new URL('assets/js/CATALOG-ICON-LICENSE.txt', root), 'Lucide 1.53.0 - https://lucide.dev/license\n\n' + await readFile(new URL('node_modules/lucide/LICENSE', root), 'utf8'));
process.stdout.write(`Catalog ${globalThis.DongDaCatalog.version}: ${catalog.all.length} validated entries, local Lucide icons generated.\n`);
