Foreground yes
LogTime yes
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
FixStaleSocket yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
StreamMaxLength 5M
MaxThreads 2
MaxQueue 4
ReadTimeout 15
CommandReadTimeout 5
ConcurrentDatabaseReload no
SelfCheck 60
ScanArchive yes
ScanPDF yes
AlertEncrypted yes
AlertExceedsMax yes
MaxScanTime 5000
MaxScanSize 25M
MaxFileSize 5M
MaxRecursion 8
MaxFiles 128
BytecodeTimeout 1000
